name: Build and publish to Helkor Docker Registry
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    push:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: docker/setup-qemu-action@v1
            - uses: docker/setup-buildx-action@v1
              with:
                  version: "v0.5.1"
                  buildkitd-flags: --debug
            - uses: docker/login-action@v1
              with:
                  registry: docker.repository.helkor.eu
                  username: helkor
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
            - uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./docker/Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      docker.repository.helkor.eu/helkor/cdn:latest
